-- name: CreateGameRule :one
INSERT INTO game_rules (
  game_id,
  group_id,
  mahjong_type,
  initial_points,
  return_points,
  ranking_points_first,
  ranking_points_second,
  ranking_points_third,
  ranking_points_fourth,
  fractional_calculation,
  use_bust,
  bust_point,
  use_chip,
  chip_point
)
VALUES (
  @game_id,
  @group_id,
  @mahjong_type,
  @initial_points,
  @return_points,
  @ranking_points_first,
  @ranking_points_second,
  @ranking_points_third,
  @ranking_points_fourth,
  @fractional_calculation,
  @use_bust,
  @bust_point,
  @use_chip,
  @chip_point
)
RETURNING
  id,
  game_id,
  group_id,
  mahjong_type,
  initial_points,
  return_points,
  ranking_points_first,
  ranking_points_second,
  ranking_points_third,
  ranking_points_fourth,
  fractional_calculation,
  use_bust,
  bust_point,
  use_chip,
  chip_point,
  created_at,
  updated_at;

-- name: GetGameRuleByGameID :one
SELECT
  id,
  game_id,
  group_id,
  mahjong_type,
  initial_points,
  return_points,
  ranking_points_first,
  ranking_points_second,
  ranking_points_third,
  ranking_points_fourth,
  fractional_calculation,
  use_bust,
  bust_point,
  use_chip,
  chip_point,
  created_at,
  updated_at
FROM
  game_rules
WHERE
  game_id = @game_id;
