// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_scores.sql

package sqlc

import (
	"context"

	null "github.com/guregu/null/v6"
)

type CreateGameScoresParams struct {
	GameID    int64    `json:"game_id"`
	GroupID   int64    `json:"group_id"`
	MemberID  int64    `json:"member_id"`
	Seat      int32    `json:"seat"`
	Ranking   int32    `json:"ranking"`
	RawScore  int32    `json:"raw_score"`
	Point     float64  `json:"point"`
	ChipCount null.Int `json:"chip_count"`
	IsBusted  bool     `json:"is_busted"`
}

const listGameScoresByGameID = `-- name: ListGameScoresByGameID :many
SELECT
  id,
  game_id,
  group_id,
  member_id,
  seat,
  ranking,
  raw_score,
  point,
  chip_count,
  is_busted,
  created_at,
  updated_at
FROM
  game_scores
WHERE
  game_id = $1
ORDER BY
  ranking
`

func (q *Queries) ListGameScoresByGameID(ctx context.Context, gameID int64) ([]GameScore, error) {
	rows, err := q.db.Query(ctx, listGameScoresByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameScore
	for rows.Next() {
		var i GameScore
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.GroupID,
			&i.MemberID,
			&i.Seat,
			&i.Ranking,
			&i.RawScore,
			&i.Point,
			&i.ChipCount,
			&i.IsBusted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
