// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (group_id, note, played_at)
VALUES ($1, $2, $3)
RETURNING id, group_id, note, played_at, created_at, updated_at
`

type CreateGameParams struct {
	GroupID  int64              `json:"group_id"`
	Note     pgtype.Text        `json:"note"`
	PlayedAt pgtype.Timestamptz `json:"played_at"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.GroupID, arg.Note, arg.PlayedAt)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Note,
		&i.PlayedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGamesByGroupID = `-- name: ListGamesByGroupID :many
SELECT
  id,
  group_id,
  note,
  played_at,
  created_at,
  updated_at
FROM
  games
WHERE
  group_id = $1
ORDER BY
  played_at DESC, id DESC
`

func (q *Queries) ListGamesByGroupID(ctx context.Context, groupID int64) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Note,
			&i.PlayedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
