// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package sqlc

import (
	"context"

	null "github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (
  group_id,
  mahjong_type,
  initial_points,
  return_points,
  ranking_points_first,
  ranking_points_second,
  ranking_points_third,
  ranking_points_fourth,
  fractional_calculation,
  fractional_recipient,
  use_bust,
  bust_point,
  use_chip,
  chip_point
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14
)
RETURNING
  id,
  group_id,
  mahjong_type,
  initial_points,
  return_points,
  ranking_points_first,
  ranking_points_second,
  ranking_points_third,
  ranking_points_fourth,
  fractional_calculation,
  fractional_recipient,
  use_bust,
  bust_point,
  use_chip,
  chip_point,
  created_at,
  updated_at
`

type CreateRuleParams struct {
	GroupID               int64    `json:"group_id"`
	MahjongType           int32    `json:"mahjong_type"`
	InitialPoints         int32    `json:"initial_points"`
	ReturnPoints          int32    `json:"return_points"`
	RankingPointsFirst    int32    `json:"ranking_points_first"`
	RankingPointsSecond   int32    `json:"ranking_points_second"`
	RankingPointsThird    int32    `json:"ranking_points_third"`
	RankingPointsFourth   null.Int `json:"ranking_points_fourth"`
	FractionalCalculation int32    `json:"fractional_calculation"`
	FractionalRecipient   null.Int `json:"fractional_recipient"`
	UseBust               bool     `json:"use_bust"`
	BustPoint             null.Int `json:"bust_point"`
	UseChip               bool     `json:"use_chip"`
	ChipPoint             null.Int `json:"chip_point"`
}

type CreateRuleRow struct {
	ID                    int64              `json:"id"`
	GroupID               int64              `json:"group_id"`
	MahjongType           int32              `json:"mahjong_type"`
	InitialPoints         int32              `json:"initial_points"`
	ReturnPoints          int32              `json:"return_points"`
	RankingPointsFirst    int32              `json:"ranking_points_first"`
	RankingPointsSecond   int32              `json:"ranking_points_second"`
	RankingPointsThird    int32              `json:"ranking_points_third"`
	RankingPointsFourth   null.Int           `json:"ranking_points_fourth"`
	FractionalCalculation int32              `json:"fractional_calculation"`
	FractionalRecipient   null.Int           `json:"fractional_recipient"`
	UseBust               bool               `json:"use_bust"`
	BustPoint             null.Int           `json:"bust_point"`
	UseChip               bool               `json:"use_chip"`
	ChipPoint             null.Int           `json:"chip_point"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (CreateRuleRow, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.GroupID,
		arg.MahjongType,
		arg.InitialPoints,
		arg.ReturnPoints,
		arg.RankingPointsFirst,
		arg.RankingPointsSecond,
		arg.RankingPointsThird,
		arg.RankingPointsFourth,
		arg.FractionalCalculation,
		arg.FractionalRecipient,
		arg.UseBust,
		arg.BustPoint,
		arg.UseChip,
		arg.ChipPoint,
	)
	var i CreateRuleRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.MahjongType,
		&i.InitialPoints,
		&i.ReturnPoints,
		&i.RankingPointsFirst,
		&i.RankingPointsSecond,
		&i.RankingPointsThird,
		&i.RankingPointsFourth,
		&i.FractionalCalculation,
		&i.FractionalRecipient,
		&i.UseBust,
		&i.BustPoint,
		&i.UseChip,
		&i.ChipPoint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuleByGroupID = `-- name: GetRuleByGroupID :one
SELECT
  id,
  group_id,
  mahjong_type,
  initial_points,
  return_points,
  ranking_points_first,
  ranking_points_second,
  ranking_points_third,
  ranking_points_fourth,
  fractional_calculation,
  use_bust,
  bust_point,
  use_chip,
  chip_point,
  created_at,
  updated_at,
  fractional_recipient
FROM
  rules
WHERE
  group_id = $1
`

func (q *Queries) GetRuleByGroupID(ctx context.Context, groupID int64) (Rule, error) {
	row := q.db.QueryRow(ctx, getRuleByGroupID, groupID)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.MahjongType,
		&i.InitialPoints,
		&i.ReturnPoints,
		&i.RankingPointsFirst,
		&i.RankingPointsSecond,
		&i.RankingPointsThird,
		&i.RankingPointsFourth,
		&i.FractionalCalculation,
		&i.UseBust,
		&i.BustPoint,
		&i.UseChip,
		&i.ChipPoint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FractionalRecipient,
	)
	return i, err
}
