// Code generated by govalid; DO NOT EDIT.
package in

import (
	"errors"

	"github.com/okm321/mahking/go/internal/domain"
	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilRules is returned when the Rules is nil.
	ErrNilRules = errors.New("input Rules is nil")

	// ErrRulesMahjongTypeEnumValidation is the error returned when the value is not in the allowed enum values domain.MahjongTypeThree, domain.MahjongTypeFour.
	ErrRulesMahjongTypeEnumValidation = govaliderrors.ValidationError{Reason: "field MahjongType must be one of domain.MahjongTypeThree, domain.MahjongTypeFour", Path: "Rules.MahjongType", Type: "enum"}

	// ErrRulesMahjongTypeRequiredValidation is returned when the MahjongType is required but not provided.
	ErrRulesMahjongTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field MahjongType is required", Path: "Rules.MahjongType", Type: "required"}

	// ErrRulesInitialPointsGTEValidation is the error returned when the value of the field is less than 1.
	ErrRulesInitialPointsGTEValidation = govaliderrors.ValidationError{Reason: "field InitialPoints must be greater than or equal to 1", Path: "Rules.InitialPoints", Type: "gte"}

	// ErrRulesInitialPointsRequiredValidation is returned when the InitialPoints is required but not provided.
	ErrRulesInitialPointsRequiredValidation = govaliderrors.ValidationError{Reason: "field InitialPoints is required", Path: "Rules.InitialPoints", Type: "required"}

	// ErrRulesReturnPointsGTEValidation is the error returned when the value of the field is less than 1.
	ErrRulesReturnPointsGTEValidation = govaliderrors.ValidationError{Reason: "field ReturnPoints must be greater than or equal to 1", Path: "Rules.ReturnPoints", Type: "gte"}

	// ErrRulesReturnPointsRequiredValidation is returned when the ReturnPoints is required but not provided.
	ErrRulesReturnPointsRequiredValidation = govaliderrors.ValidationError{Reason: "field ReturnPoints is required", Path: "Rules.ReturnPoints", Type: "required"}

	// ErrRulesRankingPointsFirstRequiredValidation is returned when the RankingPointsFirst is required but not provided.
	ErrRulesRankingPointsFirstRequiredValidation = govaliderrors.ValidationError{Reason: "field RankingPointsFirst is required", Path: "Rules.RankingPointsFirst", Type: "required"}

	// ErrRulesRankingPointsSecondRequiredValidation is returned when the RankingPointsSecond is required but not provided.
	ErrRulesRankingPointsSecondRequiredValidation = govaliderrors.ValidationError{Reason: "field RankingPointsSecond is required", Path: "Rules.RankingPointsSecond", Type: "required"}

	// ErrRulesRankingPointsThirdRequiredValidation is returned when the RankingPointsThird is required but not provided.
	ErrRulesRankingPointsThirdRequiredValidation = govaliderrors.ValidationError{Reason: "field RankingPointsThird is required", Path: "Rules.RankingPointsThird", Type: "required"}

	// ErrRulesRankingPointsFourCELValidation is the error returned when the CEL expression evaluation fails.
	ErrRulesRankingPointsFourCELValidation = govaliderrors.ValidationError{Reason: "field RankingPointsFour failed CEL validation: this.MahjongType != 2 || value.Valid", Path: "Rules.RankingPointsFour", Type: "cel"}

	// ErrRulesFractionalCalculationRequiredValidation is returned when the FractionalCalculation is required but not provided.
	ErrRulesFractionalCalculationRequiredValidation = govaliderrors.ValidationError{Reason: "field FractionalCalculation is required", Path: "Rules.FractionalCalculation", Type: "required"}

	// ErrRulesUseBustRequiredValidation is returned when the UseBust is required but not provided.
	ErrRulesUseBustRequiredValidation = govaliderrors.ValidationError{Reason: "field UseBust is required", Path: "Rules.UseBust", Type: "required"}

	// ErrRulesUseChipRequiredValidation is returned when the UseChip is required but not provided.
	ErrRulesUseChipRequiredValidation = govaliderrors.ValidationError{Reason: "field UseChip is required", Path: "Rules.UseChip", Type: "required"}
)

func Validaterules(t *Rules) error {
	if t == nil {
		return ErrNilRules
	}

	var errs govaliderrors.ValidationErrors

	if t.MahjongType != domain.MahjongTypeThree && t.MahjongType != domain.MahjongTypeFour {
		err := ErrRulesMahjongTypeEnumValidation
		err.Value = t.MahjongType
		errs = append(errs, err)
	}

	if t.MahjongType == 0 {
		err := ErrRulesMahjongTypeRequiredValidation
		err.Value = t.MahjongType
		errs = append(errs, err)
	}

	if !(t.InitialPoints >= 1) {
		err := ErrRulesInitialPointsGTEValidation
		err.Value = t.InitialPoints
		errs = append(errs, err)
	}

	if t.InitialPoints == 0 {
		err := ErrRulesInitialPointsRequiredValidation
		err.Value = t.InitialPoints
		errs = append(errs, err)
	}

	if !(t.ReturnPoints >= 1) {
		err := ErrRulesReturnPointsGTEValidation
		err.Value = t.ReturnPoints
		errs = append(errs, err)
	}

	if t.ReturnPoints == 0 {
		err := ErrRulesReturnPointsRequiredValidation
		err.Value = t.ReturnPoints
		errs = append(errs, err)
	}

	if t.RankingPointsFirst == 0 {
		err := ErrRulesRankingPointsFirstRequiredValidation
		err.Value = t.RankingPointsFirst
		errs = append(errs, err)
	}

	if t.RankingPointsSecond == 0 {
		err := ErrRulesRankingPointsSecondRequiredValidation
		err.Value = t.RankingPointsSecond
		errs = append(errs, err)
	}

	if t.RankingPointsThird == 0 {
		err := ErrRulesRankingPointsThirdRequiredValidation
		err.Value = t.RankingPointsThird
		errs = append(errs, err)
	}

	if !((t.MahjongType != 2) || (t.RankingPointsFour.Valid)) {
		err := ErrRulesRankingPointsFourCELValidation
		err.Value = t.RankingPointsFour
		errs = append(errs, err)
	}

	if t.FractionalCalculation == 0 {
		err := ErrRulesFractionalCalculationRequiredValidation
		err.Value = t.FractionalCalculation
		errs = append(errs, err)
	}

	if t.UseBust == false {
		err := ErrRulesUseBustRequiredValidation
		err.Value = t.UseBust
		errs = append(errs, err)
	}

	if t.UseChip == false {
		err := ErrRulesUseChipRequiredValidation
		err.Value = t.UseChip
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Rules)(nil)

func (t *Rules) Validate() error {
	return Validaterules(t)
}
