services:
  postgres-db:
    image: postgres:18
    volumes:
      - ./postgres-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: postgres
      TZ: Asia/Tokyo
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGPASSWORD: "password"
    command: postgres -c max_locks_per_transaction=1024 -c fsync=off
